language: node_js
node_js:
- "0.12"
- 4
- 5
- iojs-v2
- iojs-v3
os:
- linux
- osx
before_install:
- "[ $TRAVIS_OS_NAME=osx ] && brew update"
- "[ $TRAVIS_OS_NAME=osx ] && (brew outdated nvm || brew upgrade nvm)"
after_success:
  - npm run coveralls
